import img1 from './../images/1.jpg';
import img2 from './../images/2.jpg';
import img3 from './../images/3.jpg';
import img4 from './../images/4.jpg';
import img5 from './../images/5.jpg';

export const PRODUCTS = [
  {
    id: '2',
    title: 'Детская зимняя куртка2',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Комплект карандашей с ластиком. Самый базовый...',
    orderQuantity: 10,
    colors: [{ color: 'white' }, { color: 'violet' }, { color: 'yellow' }],
    price: 4000,
    commentsCount: 20,
    rating: 4.8,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 800,
    minOrder: 5,
    images: [img4, img3, img5, img4, img3, img5, img2, img2],
  },
  {
    id: '3',
    title: 'Детская зимняя куртка3',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img1, img3, img2, img1],
  },
  {
    id: '4',
    title: 'Детская зимняя куртка4',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img1, img3, img2],
  },
  {
    id: '5',
    title: 'Детская зимняя куртка5',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: false,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    images: [img1, img3],
  },
  {
    id: '6',
    title: 'Детская зимняя куртка6',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: false,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img1, img3, img5, img2, img4],
  },
  {
    id: '7',
    title: 'Детская зимняя куртка7',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: false,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img1, img2, img4],
  },
  {
    id: '8',
    title: 'Детская зимняя куртка8',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img2, img4],
  },
  {
    id: '9',
    title: 'Детская зимняя куртка9',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 198,
    rating: 4.8,
    minOrder: 5,
    images: [img1, img3, img5, img2, img4],
  },
  {
    id: '10',
    title: 'Детская зимняя куртка10',
    shipper: 'ООО "Компания"',
    productCode: 1234567,
    availableStatus: true,
    description:
      'Куртка зимняя, утепленная, выполнена из прочной, износостойкой, влагостойкой ткани...',
    orderQuantity: 10,
    colors: [{ color: 'red' }, { color: 'green' }, { color: 'black' }],
    price: 4000,
    commentsCount: 20,
    unit: 'шт',
    piecesAll: 2000,
    piecesNow: 1598,
    rating: 4.8,
    minOrder: 5,
    images: [img1],
  },
];
